POST http://www.makinteract.com/api/image/generate  
Content-Type: application/json

{
  "prompt": "mutated korean man, with glasses, bowl cut hairstyle, black hoodie, gray pants, with a baseball in his hand, photorealistic",
  "steps": 4
}