FROM node:25-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG API_BASE
ENV API_BASE=$API_BASE

RUN npm run build
RUN npm install -g serve

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
